"use client"
import AppShell from "@/components/app-shell"
import MobileNotifications from "@/components/mobile-notifications"
import { AlertTriangle, Database, Download, Moon, ShieldCheck, Sun, Trash2, X } from "lucide-react"
import { useEffect, useState } from "react"

export default function Settings(){
  const[theme,setTheme]=useState<"dark"|"light">("dark");const[confirm,setConfirm]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("")
  useEffect(()=>{const saved=(localStorage.getItem("theme") as "dark"|"light")||"dark";setTheme(saved);document.documentElement.classList.remove("dark","light");document.documentElement.classList.add(saved)},[])
  function toggle(){const next=theme==="dark"?"light":"dark";setTheme(next);localStorage.setItem("theme",next);document.documentElement.classList.remove("dark","light");document.documentElement.classList.add(next)}
  async function clear(){setBusy(true);setMsg("");const r=await fetch("/api/settings/clear-data",{method:"DELETE"});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMsg(d.error||"Could not clear data");return}setConfirm(false);setMsg(d.message||"All financial data cleared successfully.")}
  return <AppShell><p className="eyebrow">Workspace</p><h2 className="mt-2 text-3xl font-black">Settings</h2><p className="mt-2 muted">Privacy, appearance and data controls.</p>{msg&&<div className="soft-panel mt-5 text-sm">{msg}</div>}<div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="soft-panel"><ShieldCheck className="accent"/><h3 className="mt-4 font-black">Privacy</h3><p className="mt-2 text-sm leading-6 muted">Your financial records are scoped to your authenticated user account.</p></div><div className="soft-panel"><Database className="accent"/><h3 className="mt-4 font-black">Export your data</h3><p className="mt-2 text-sm muted">Download expense transactions as CSV.</p><a href="/api/export" className="btn btn-secondary mt-4"><Download size={17}/>Download CSV</a></div><div className="soft-panel"><div className="flex items-center justify-between gap-4"><div>{theme==="dark"?<Moon className="accent"/>:<Sun className="accent"/>}<h3 className="mt-4 font-black">Appearance</h3><p className="mt-2 text-sm muted">Switch between dark and light mode.</p></div><button onClick={toggle} className={`relative h-8 w-16 rounded-full p-1 ${theme==="light"?"bg-emerald-300":"bg-white/10"}`}><span className={`block h-6 w-6 rounded-full bg-emerald-950 transition-transform ${theme==="light"?"translate-x-8":"translate-x-0"}`}/></button></div></div></div><MobileNotifications/><div className="danger-panel mt-8"><div className="flex gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-red-500/10 text-red-400"><Trash2 size={20}/></div><div><h3 className="font-black text-red-300">Danger Zone</h3><p className="mt-2 text-sm muted">Delete all expenses, income, budgets and financial records while keeping your login account.</p><button onClick={()=>setConfirm(true)} className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-2 text-sm font-bold text-red-300">Clear all data</button></div></div></div>{confirm&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="modal-panel w-full max-w-md rounded-3xl border p-6"><div className="flex justify-between"><AlertTriangle className="text-red-400"/><button onClick={()=>setConfirm(false)}><X/></button></div><h3 className="mt-5 text-xl font-black">Clear all data?</h3><p className="mt-3 text-sm muted">This permanently deletes your financial data and cannot be undone.</p><div className="mt-6 flex gap-3 justify-end"><button onClick={()=>setConfirm(false)} className="btn btn-secondary">Cancel</button><button onClick={clear} disabled={busy} className="rounded-xl bg-red-500 px-4 py-2 font-bold text-white">{busy?"Clearing...":"Clear everything"}</button></div></div></div>}</AppShell>
}
